### ISSUE TITLE
Create Activity and Facebook Auth

### ISSUE THREAD

**Issue by sleque** [MeetPoint-App/meetpoint-ios#2]
Thank you for sharing this project as open-source. 

Small error was fixed by simply Activating the FB APP.

EDIT2: I now have notice that I am unable to navigate to "Newest Users List" pane and when I search for a user, it does not find any users. Near Me and Discover also return back no results.

**Comment by sleque** [comment]
Facebook is still sign-up / login is still returning the same issue.
<img width="676" alt="screen shot 2018-08-21 at 12 19 06 am" src="https://user-images.githubusercontent.com/36781803/44380184-e7e0e680-a4d7-11e8-80fd-d54d575283e6.png">

**Comment by yusufkildan** [comment]
Hi sleque, thanks for your help. To navigate "Newest Users List" you have to add Top Users manually to database. For example: 
<img width="495" alt="screenshot at aug 21 12-31-56" src="https://user-images.githubusercontent.com/7632833/44393821-5e183400-a53e-11e8-9157-90eb869fbe43.png">

Also, can you send me the error message of Facebook login? I checked it, it works fine.
